<?php


namespace fecbbc\models\mysqldb;


use yii\db\ActiveRecord;
use yii\web\IdentityInterface;

class Notices extends ActiveRecord implements IdentityInterface
{
    public static function tableName(): string
    {
        return '{{%notices}}';
    }

    public static function findIdentity($id)
    {
        return static::findOne(['id' => $id, 'status' => self::STATUS_ACTIVE]);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    public function getId()
    {
        return $this->getPrimaryKey();
    }

    public function getAuthKey()
    {
        // TODO: Implement getAuthKey() method.
    }

    public function validateAuthKey($authKey)
    {
        // TODO: Implement validateAuthKey() method.
    }

    public function insert($runValidation = true, $attributes = null)
    {
        return parent::insert($runValidation, $attributes); // TODO: Change the autogenerated stub
    }
}
